### ISSUE TITLE
Set Kanban Board

### ISSUE THREAD

**Issue by nicupop729** [nicupop729/space-travellers-hub#45]
### The link for the project is [this one](https://github.com/nicupop729/space-travelers-hub).

For this activity, we are two team members:
**@nicupop729**
**@Chike1990**

**Comment by omar-labana** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
